# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # CKS -Kubernetes Master Server
  config.vm.define "cksmaster" do |cksmaster|
    cksmaster.vm.box = "bento/ubuntu-18.04"
    cksmaster.vm.hostname = "cks-master.example.com"
    cksmaster.vm.network "private_network", ip: "172.42.42.100"
    cksmaster.vm.provider "virtualbox" do |v|
      v.name = "cks-master"
      v.memory = 2048
      v.cpus = 2
    end
    cksmaster.vm.provision "shell", path: "bootstrap_cksmaster.sh"
  end

  NodeCount = 2

  # CKS - Kubernetes Worker Nodes 
  (1..NodeCount).each do |i|
    config.vm.define "cksworker#{i}" do |workernode|
      workernode.vm.box = "bento/ubuntu-18.04"
      workernode.vm.hostname = "cks-worker#{i}.example.com"
      workernode.vm.network "private_network", ip: "172.42.42.10#{i}"
      workernode.vm.provider "virtualbox" do |v|
        v.name = "cks-worker#{i}"
        v.memory = 2048
        v.cpus = 1
      end
      workernode.vm.provision "shell", path: "bootstrap_cksworker.sh"
    end
  end

end
